safe:         false
highlighters: pygments
markdown:     redcarpet
permalink:    /:year/:month/:day/:title
exclude:      ["CNAME", "Rakefile", "old.Gemfile", "old.Gemfile.lock"]
title:        gatillos.com - gun-toting kittens
baseurl:      /yay
url_root:     https://gatillos.com
url_root_nossl: http://gatillos.com
import_location: https://gatillos.com/yay
author:       osuka
author_short: osuka
author_email: webmaster@gatillos.com
analytics_ua: UA-15027129-1
feedburner_id: gatillos
disqus_id:     gatillos
paginate:     10
